# Generated by Django 6.0 on 2025-12-19 20:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_gender_profile_is_complete_and_more'),
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='from_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_sent', to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='to_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='profile1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_profile1', to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='profile2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_profile2', to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('from_profile', 'to_profile')},
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('profile1', 'profile2')},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        'ALTER TABLE "interactions_match" ALTER COLUMN "id" DROP IDENTITY IF EXISTS;',
                        'ALTER TABLE "interactions_match" ALTER COLUMN "id" TYPE uuid USING (lpad(to_hex("id"), 32, \'0\')::uuid);',
                    ],
                    reverse_sql=[
                        'ALTER TABLE "interactions_match" ALTER COLUMN "id" TYPE bigint;',
                    ],
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='match',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='like',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user2',
        ),
    ]
