# Generated by Django 6.0 on 2025-12-21 10:55

import uuid
from django.db import migrations, models


def convert_profile_id_to_uuid(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    schema_editor.execute(
        'ALTER TABLE "accounts_profile" ALTER COLUMN "id" DROP IDENTITY IF EXISTS;'
    )
    schema_editor.execute(
        'ALTER TABLE "accounts_profile" ALTER COLUMN "id" TYPE uuid '
        'USING (lpad(to_hex("id"), 32, \'0\')::uuid);'
    )


def convert_profile_id_to_bigint(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    schema_editor.execute(
        'ALTER TABLE "accounts_profile" ALTER COLUMN "id" TYPE bigint;'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_gender_profile_is_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='children_status',
            field=models.CharField(blank=True, choices=[('none', 'No children'), ('have_children', 'Have children'), ('want_children', 'Want children'), ('dont_want', "Don't want children"), ('open', 'Open to children')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='diagnosis_year',
            field=models.IntegerField(blank=True, help_text='Year of diagnosis (YYYY) - completely optional and private', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='disclosure_comfort',
            field=models.CharField(blank=True, choices=[('very_comfortable', 'Very comfortable discussing'), ('somewhat_comfortable', 'Somewhat comfortable'), ('private', 'Keep private')], max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='drinking',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('socially', 'Socially'), ('regularly', 'Regularly')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('retired', 'Retired'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.TextField(blank=True, help_text='Comma-separated hobbies and interests'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_completeness',
            field=models.IntegerField(default=0, help_text='Percentage 0-100'),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoking',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('occasionally', 'Occasionally'), ('regularly', 'Regularly'), ('trying_to_quit', 'Trying to quit')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='support_seeking',
            field=models.BooleanField(default=False, help_text='Looking for community support'),
        ),
        migrations.AddField(
            model_name='profile',
            name='treatment_status',
            field=models.CharField(blank=True, choices=[('on_treatment', 'On treatment'), ('not_on_treatment', 'Not on treatment'), ('undetectable', 'Undetectable viral load'), ('prefer_not_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    convert_profile_id_to_uuid,
                    convert_profile_id_to_bigint,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='profile',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='General area', max_length=255),
        ),
    ]
