# Generated by Django 6.0 on 2026-02-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='app_variant',
            field=models.CharField(choices=[('hiv_plus', 'HIV+ Community'), ('general', 'Diverse Hearts')], default='hiv_plus', help_text='The app variant this profile belongs to', max_length=20),
        ),
    ]
