# Generated by Django 6.0 on 2026-02-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0006_alter_preference_pref_ethnicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='pref_residence_country',
            field=models.CharField(blank=True, choices=[('', 'Select Country'), ('Zimbabwe', 'Zimbabwe'), ('South Africa', 'South Africa'), ('Botswana', 'Botswana'), ('Namibia', 'Namibia'), ('Zambia', 'Zambia'), ('Malawi', 'Malawi'), ('Mozambique', 'Mozambique'), ('Lesotho', 'Lesotho'), ('Swaziland', 'Swaziland'), ('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Tanzania', 'Tanzania'), ('Burundi', 'Burundi'), ('Rwanda', 'Rwanda'), ('Other', 'Other')], help_text='Preferred country of residence', max_length=100),
        ),
    ]
